In [1]:
import pandas as pd
import numpy as np
import googlemaps

from geopy.distance import geodesic

# Importar datos
- geocode eds con tienda
- geocode eds sin tienda
- geocode oxxo RM

In [2]:
# Importar geocode de eds con tienda
geocode_eds_con_tienda_df = pd.read_csv('geocode_eds_con_tienda.csv', sep=';')
geocode_eds_con_tienda_df

codigo_sap  codigo_eds                 tienda   marca      formato  \
0          2009       10096           Pozo Almonte  Pronto        Barra   
1          2013       20012     San Rafael Oriente  Pronto        Barra   
2          2012       20017     San Carlos Oriente  Pronto        Barra   
3          2056       20089           Puerto Varas  Pronto        Barra   
4          2055       20091        Trafún Poniente  Pronto        Barra   
..          ...         ...                    ...     ...          ...   
408          -1       10436  AVDA. 27 DE ABRIL S/N   PUNTO    Foodtruck   
409          -1       40183      La Serena Ruta 41   PUNTO  Punto Copec   
410          -1       40188                  Olmué   PUNTO  Punto Copec   
411          -1       10617       ANIBAL PINTO 400   PUNTO     Punto AP   
412          -1       20011                Coronel   PUNTO  Punto Copec   

       mercado                     direccion            comuna      region  \
0    Carretera    Panamericana norte km 1810      Pozo Almonte    Tarapacá   
1    Carretera             RUTA 5 SUR KM 237        San Rafael       Maule   
2    Carretera           RUTA 5 SUR KM 383,3        San Carlos       Ñuble   
3    Carretera         RUTA 5 SUR KM 1009,4.      Puerto Varas   Los Lagos   
4    Carretera  RUTA 5 SUR KM. 904,3 TRAFUN.         San Pablo   Los Lagos   
..         ...                           ...               ...         ...   
408     Urbana           AV. 27 DE ABRIL S/N              PICA    TARAPACA   
409     Urbana              COLO COLO N°5300         LA SERENA    COQUIMBO   
410     Urbana        AV ADOLFO EASTMAN 2603             OLMUÉ  VALPARAISO   
411     Urbana                 Punto Iquique  DIEGO DE ALMAGRO     ATACAMA   
412     Urbana                SOTOMAYOR 1300           CORONEL      BIOBIO   

         EDS Zona                Dirección  Región   Provincia     Comuna  \
0        NaN  NaN                      NaN     NaN         NaN        NaN   
1        NaN  NaN                      NaN     NaN         NaN        NaN   
2        NaN  NaN                      NaN     NaN         NaN        NaN   
3        NaN  NaN                      NaN     NaN         NaN        NaN   
4        NaN  NaN                      NaN     NaN         NaN        NaN   
..       ...  ...                      ...     ...         ...        ...   
408  10436.0  OZN      AV. 27 DE ABRIL S/N     1.0    TARAPACÁ       PICA   
409  40183.0  OZC         COLO COLO N°5300     4.0   LA SERENA  LA SERENA   
410  40188.0  OZC  AV. ADOLFO EASTMAN 2603     5.0  VALPARAÍSO      OLMUE   
411      NaN  NaN                      NaN     NaN         NaN        NaN   
412  20011.0  OZS       AV. SOTOMAYOR 1300     8.0  CONCEPCIÓN    CORONEL   

    Fecha Apertura  Latitud  Longitud  nueva_latitud  nueva_longitud  
0              NaN      0.0       0.0     -20.256215      -69.785726  
1              NaN      0.0       0.0     -35.291348      -71.507893  
2              NaN      0.0       0.0     -30.627836      -71.501985  
3              NaN      0.0       0.0     -41.351871      -72.986542  
4              NaN      0.0       0.0     -40.411073      -73.001857  
..             ...      ...       ...            ...             ...  
408     2021-06-10      0.0       0.0     -20.489483      -69.330511  
409     2021-07-01      0.0       0.0     -29.920573      -71.195887  
410     2021-07-08      0.0       0.0     -32.998804      -71.215087  
411            NaN      0.0       0.0     -26.390249      -70.047530  
412     2021-08-18      0.0       0.0     -37.035319      -73.141808  

[413 rows x 20 columns]

In [3]:
# Importar geocode de eds sin tienda
geocode_eds_sin_tienda_df = pd.read_csv('geocode_eds_sin_tienda.csv', sep=';')
geocode_eds_sin_tienda_df.fillna(0, inplace=True)
geocode_eds_sin_tienda_df

codigo_sap  codigo_eds tienda           marca formato mercado  \
0            -1       10005      -  EDS Sin Tienda       -       -   
1            -1       10009      -  EDS Sin Tienda       -       -   
2            -1       10025      -  EDS Sin Tienda       -       -   
3            -1       10040      -  EDS Sin Tienda       -       -   
4            -1       10194      -  EDS Sin Tienda       -       -   
..          ...         ...    ...             ...     ...     ...   
260          -1       60561      -  EDS Sin Tienda       -       -   
261          -1       60758      -  EDS Sin Tienda       -       -   
262          -1       60824      -  EDS Sin Tienda       -       -   
263          -1       60838      -  EDS Sin Tienda       -       -   
264          -1       60999      -  EDS Sin Tienda       -       -   

                                        direccion            comuna  \
0                              AV. EL TOFO N° 043  DIEGO DE ALMAGRO   
1               AV. MEJILLONES 4950, ESQ. ILLAPEL       ANTOFAGASTA   
2                            RUTA 5 NORTE KM 1398       ANTOFAGASTA   
3                               SAN MARTIN N° 699             ARICA   
4                          PANAMERICANA NORTE S/N      SIERRA GORDA   
..                                            ...               ...   
260                  30 KM AL NORESTE DE RANCAGUA           MACHALÍ   
261  CARDENAL CARO S/N ESQ. OBISPO LARRAÍN N° 792          LITUECHE   
262                        AV. LA FLORIDA N° 7165        LA FLORIDA   
263                      CAMINO A PICHILEMU KM 65         PERALILLO   
264                     AV. INDEPENDENCIA N° 1517     INDEPENDENCIA   

                 region  EDS Zona Dirección  Región Provincia Comuna  \
0               ATACAMA  0.0    0         0     0.0         0      0   
1           ANTOFAGASTA  0.0    0         0     0.0         0      0   
2           ANTOFAGASTA  0.0    0         0     0.0         0      0   
3    ARICA Y PARINACOTA  0.0    0         0     0.0         0      0   
4           ANTOFAGASTA  0.0    0         0     0.0         0      0   
..                  ...  ...  ...       ...     ...       ...    ...   
260           O HIGGINS  0.0    0         0     0.0         0      0   
261           O HIGGINS  0.0    0         0     0.0         0      0   
262       METROPOLITANA  0.0    0         0     0.0         0      0   
263           O HIGGINS  0.0    0         0     0.0         0      0   
264       METROPOLITANA  0.0    0         0     0.0         0      0   

    Fecha Apertura  Latitud  Longitud  nueva_latitud  nueva_longitud  
0                0      0.0       0.0     -26.250968      -69.626347  
1                0      0.0       0.0     -23.625154      -70.391202  
2                0      0.0       0.0     -30.777949      -71.554519  
3                0      0.0       0.0     -18.479824      -70.313511  
4                0      0.0       0.0     -23.105991      -69.608076  
..             ...      ...       ...            ...             ...  
260              0      0.0       0.0     -34.179452      -70.656515  
261              0      0.0       0.0     -34.117735      -71.729929  
262              0      0.0       0.0     -33.520487      -70.580491  
263              0      0.0       0.0     -34.518611      -71.970278  
264              0      0.0       0.0     -33.413149      -70.658148  

[265 rows x 20 columns]

In [4]:
# Importar geocode de oxxo
geocode_oxxo_df = pd.read_csv('geocode_oxxo.csv', sep=';')
geocode_oxxo_df

address  nueva_latitud  \
0   Bandera 177, Santiago, Región Metropolitana, C...     -33.441155   
1   General Mackenna 1010. Estación Metro Cal y Ca...     -33.433147   
2   Morandé 801, Local 102, Santiago, Región Metro...     -33.433593   
3   Agustinas 1454 Depto. 5, Santiago, Región Metr...     -33.441481   
4   Compañía de Jesús 1579, locales 4 - 5, Santiag...     -33.439172   
..                                                ...            ...   
82  San Damián N°20, Local 1B, Las Condes, Región ...     -33.376485   
83  Av. José Alcalde Delano 10581, Local 3, Lo Bar...     -33.355624   
84  Avenida La Plaza 1250, Local B, Las Condes San...     -33.395221   
85  Av. Las Condes 12340, Lo Barnechea, Región Met...     -33.372185   
86  Av. Las Condes 12523, Las Condes, Región Metro...     -33.372482   

    nueva_longitud  
0       -70.652000  
1       -70.652144  
2       -70.654314  
3       -70.657130  
4       -70.659062  
..             ...  
82      -70.524893  
83      -70.535139  
84      -70.505088  
85      -70.518382  
86      -70.515547  

[87 rows x 3 columns]

# Calcular la distancia geodésica
- entre eds con tienda y oxxo RM
- entre eds sin tienda y oxxo RM

In [5]:
# Calcular distancia entre todas las eds con tienda y las tiendas oxxo
geodesic_distance_con_tiendas = np.zeros((len(geocode_eds_con_tienda_df), len(geocode_oxxo_df)))
for i in range(0, len(geocode_eds_con_tienda_df)):
    for j in range(0, len(geocode_oxxo_df)):

        coord_eds = (geocode_eds_con_tienda_df.loc[i, ['nueva_latitud']].values[0], geocode_eds_con_tienda_df.loc[i, ['nueva_longitud']].values[0])
        coord_oxxo = (geocode_oxxo_df.loc[j, ['nueva_latitud']].values[0], geocode_oxxo_df.loc[j, ['nueva_longitud']].values[0])

        geodesic_distance_con_tiendas[i,j] = geodesic(coord_eds, coord_oxxo).km

geodesic_distance_con_tiendas

array([[1463.45995857, 1462.57434575, 1462.63637281, ..., 1457.59200927,
        1455.10555279, 1455.12455039],
       [ 219.81971032,  220.64577233,  220.52832003, ...,  229.67905337,
         231.54229729,  231.61460416],
       [ 322.12341171,  321.26080012,  321.25757136, ...,  320.99085728,
         318.18370919,  318.29356758],
       ...,
       [  71.84864742,   71.23694044,   71.12153113, ...,   79.47252124,
          77.04713068,   77.28784736],
       [ 783.77637165,  782.89187734,  782.95685428, ...,  777.76414814,
         775.28771595,  775.30469231],
       [ 458.60814704,  459.37941702,  459.23873371, ...,  469.76140987,
         471.36221011,  471.46431991]])

In [6]:
# Calcular distancia entre todas las eds con tienda y las tiendas oxxo
geodesic_distance_sin_tiendas = np.zeros((len(geocode_eds_sin_tienda_df), len(geocode_oxxo_df)))
for i in range(0, len(geocode_eds_sin_tienda_df)):
    for j in range(0, len(geocode_oxxo_df)):

        coord_eds = (geocode_eds_sin_tienda_df.loc[i, ['nueva_latitud']].values[0], geocode_eds_sin_tienda_df.loc[i, ['nueva_longitud']].values[0])
        coord_oxxo = (geocode_oxxo_df.loc[j, ['nueva_latitud']].values[0], geocode_oxxo_df.loc[j, ['nueva_longitud']].values[0])

        geodesic_distance_sin_tiendas[i,j] = geodesic(coord_eds, coord_oxxo).km

geodesic_distance_sin_tiendas

array([[ 803.15936928,  802.28021344,  802.35518137, ...,  796.47191329,
         794.07080988,  794.073978  ],
       [1088.20143251, 1087.31384709, 1087.36832874, ..., 1082.86593745,
        1080.32526442, 1080.35513084],
       [ 307.35411803,  306.49807032,  306.48876467, ...,  306.66242877,
         303.84338242,  303.96084728],
       ...,
       [  11.02698833,   11.75571699,   11.83074809, ...,   15.56188601,
          17.4328516 ,   17.49095435],
       [ 170.65108015,  171.26877903,  171.09120005, ...,  184.02901607,
         184.88769551,  185.05519129],
       [   3.15839526,    2.28721743,    2.29539367, ...,   14.3765339 ,
          13.77426514,   14.012885  ]])

In [7]:
geodesic_distance_con_tienda_df = pd.DataFrame(geodesic_distance_con_tiendas)
geodesic_distance_sin_tienda_df = pd.DataFrame(geodesic_distance_sin_tiendas)

geodesic_distance_con_tienda_df.to_csv('geodesic_distance_con_tiendas.csv', sep=';', index=False)
geodesic_distance_sin_tienda_df.to_csv('geodesic_distance_sin_tiendas.csv', sep=';', index=False)

# Carcular distancia tiempo de viaje en vehiculo (google maps api)
- entre eds con tienda y oxxo RM
- entre eds sin tienda y oxxo RM

In [17]:
import json

with open('credential.json') as json_file:
  data = json.load(json_file)

key = data["gmaps_api_key"]
gmaps = googlemaps.Client(key=key)

In [9]:
# Calcular viaje (distancia y tiempo en auto) entre todas las eds con tienda y las tiendas oxxo
gmaps_distance_con_tiendas = np.zeros((len(geocode_eds_con_tienda_df), len(geocode_oxxo_df)))
gmaps_duration_con_tiendas = np.zeros((len(geocode_eds_con_tienda_df), len(geocode_oxxo_df)))

for i in range(0, len(geocode_eds_con_tienda_df)):
    for j in range(0, len(geocode_oxxo_df)):

        coord_eds = (geocode_eds_con_tienda_df.loc[i, ['nueva_latitud']].values[0], geocode_eds_con_tienda_df.loc[i, ['nueva_longitud']].values[0])
        coord_oxxo = (geocode_oxxo_df.loc[j, ['nueva_latitud']].values[0], geocode_oxxo_df.loc[j, ['nueva_longitud']].values[0])

        result = gmaps.distance_matrix(coord_eds, coord_oxxo, mode='driving')

        if result["rows"][0]["elements"][0]["status"] == 'OK':
            gmaps_distance_con_tiendas[i, j] = result["rows"][0]["elements"][0]["distance"]["value"]
            gmaps_duration_con_tiendas[i, j] = result["rows"][0]["elements"][0]["duration"]["value"]

        else:
            gmaps_distance_con_tiendas[i, j] = -1
            gmaps_duration_con_tiendas[i, j] = -1

print(gmaps_distance_con_tiendas, gmaps_duration_con_tiendas)

[[1767599. 1767149. 1766728. ... 1782731. 1780204. 1780890.]
 [ 235762.  236974.  236968. ...  254467.  254134.  252871.]
 [ 388082.  387633.  387211. ...  403214.  400687.  401374.]
 ...
 [ 100384.   99935.   99514. ...  115517.  112989.  113676.]
 [ 949487.  949037.  948616. ...  964619.  962092.  962778.]
 [ 533086.  534298.  534292. ...  551792.  551459.  550196.]] [[68750. 68689. 68682. ... 69587. 68998. 69164.]
 [ 9076.  9049.  9101. ... 10152.  9673.  9810.]
 [14971. 14911. 14904. ... 15809. 15219. 15385.]
 ...
 [ 5693.  5633.  5626. ...  6531.  5941.  6108.]
 [36591. 36531. 36524. ... 37429. 36839. 37006.]
 [21254. 21226. 21279. ... 22330. 21851. 21988.]]


In [10]:
# Calcular viaje (distancia y tiempo en auto) entre todas las eds sin tienda y las tiendas oxxo
gmaps_distance_sin_tiendas = np.zeros((len(geocode_eds_sin_tienda_df), len(geocode_oxxo_df)))
gmaps_duration_sin_tiendas = np.zeros((len(geocode_eds_sin_tienda_df), len(geocode_oxxo_df)))

for i in range(0, len(geocode_eds_sin_tienda_df)):
    for j in range(0, len(geocode_oxxo_df)):

        coord_eds = (geocode_eds_sin_tienda_df.loc[i, ['nueva_latitud']].values[0], geocode_eds_sin_tienda_df.loc[i, ['nueva_longitud']].values[0])
        coord_oxxo = (geocode_oxxo_df.loc[j, ['nueva_latitud']].values[0], geocode_oxxo_df.loc[j, ['nueva_longitud']].values[0])

        result = gmaps.distance_matrix(coord_eds, coord_oxxo, mode='driving')

        if result["rows"][0]["elements"][0]["status"] == 'OK':
            gmaps_distance_sin_tiendas[i, j] = result["rows"][0]["elements"][0]["distance"]["value"]
            gmaps_duration_sin_tiendas[i, j] = result["rows"][0]["elements"][0]["duration"]["value"]

        else:
            gmaps_distance_sin_tiendas[i, j] = -1
            gmaps_duration_sin_tiendas[i, j] = -1

print(gmaps_distance_sin_tiendas, gmaps_duration_sin_tiendas)

[[1002195. 1001746. 1001324. ... 1017327. 1014800. 1015486.]
 [1337801. 1337351. 1336930. ... 1352933. 1350405. 1351092.]
 [ 359439.  358989.  358568. ...  374571.  372044.  372730.]
 ...
 [  22421.   23633.   23627. ...   21342.   27041.   22995.]
 [ 228296.  229508.  229502. ...  247002.  246669.  245406.]
 [   3984.    3151.    3148. ...   20647.   20314.   19051.]] [[38773. 38713. 38706. ... 39611. 39021. 39188.]
 [52927. 52866. 52859. ... 53764. 53175. 53341.]
 [13774. 13714. 13707. ... 14612. 14022. 14189.]
 ...
 [ 1709.  1682.  1734. ...  2537.  2381.  2281.]
 [12255. 12227. 12280. ... 13331. 12852. 12989.]
 [ 1026.   780.   811. ...  1910.  1430.  1568.]]


In [11]:
gmaps_distance_con_tienda_df = pd.DataFrame(gmaps_distance_con_tiendas)
gmaps_distance_sin_tienda_df = pd.DataFrame(gmaps_distance_sin_tiendas)

gmaps_duration_con_tienda_df = pd.DataFrame(gmaps_duration_con_tiendas)
gmaps_duration_sin_tienda_df = pd.DataFrame(gmaps_duration_sin_tiendas)

gmaps_distance_con_tienda_df.to_csv('gmaps_distance_con_tiendas.csv', sep=';', index=False)
gmaps_distance_sin_tienda_df.to_csv('gmaps_distance_sin_tiendas.csv', sep=';', index=False)

gmaps_duration_con_tienda_df.to_csv('gmaps_duration_con_tiendas.csv', sep=';', index=False)
gmaps_duration_sin_tienda_df.to_csv('gmaps_duration_sin_tiendas.csv', sep=';', index=False)